name: Stock Market Analysis

on:
  # 定时执行：工作日的北京时间 9:30, 11:30, 13:00, 14:00, 15:00, 16:00
  schedule:
    - cron: '30 1 * * 1-5'  # 9:30 Beijing Time
    - cron: '30 3 * * 1-5'  # 11:30 Beijing Time
    - cron: '0 5 * * 1-5'   # 13:00 Beijing Time
    - cron: '0 6 * * 1-5'   # 14:00 Beijing Time
    - cron: '0 7 * * 1-5'   # 15:00 Beijing Time
    - cron: '0 8 * * 1-5'   # 16:00 Beijing Time

  # 支持手动触发
  workflow_dispatch:
    inputs:
      custom_prompt:
        description: 'Custom analysis prompt (optional)'
        required: false
        type: string

jobs:
  analyze:
    runs-on: ubuntu-latest
    environment: production
    env:
      PYTHONIOENCODING: utf-8
    steps:
      - name: Set beijing timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneWindows: "China Standard Time"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Get npm global directory
        id: npm-global
        run: echo "dir=$(npm config get prefix)" >> $GITHUB_OUTPUT

      - name: Cache Claude CLI
        id: cache-claude
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.npm-global.outputs.dir }}
            ~/.claude
            ~/.claude.json
          key: ${{ runner.os }}-claude-cli-npm-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-claude-cli-npm-

      - name: Install Claude CLI
        if: steps.cache-claude.outputs.cache-hit != 'true'
        run: |
          echo "缓存未命中，开始安装 Claude Code..."
          npm install -g @anthropic-ai/claude-code

      - name: Add Claude CLI to PATH
        run: |
          echo "设置 Claude CLI 命令到环境中..."
          echo "${{ steps.npm-global.outputs.dir }}/bin" >> $GITHUB_PATH

      - name: Run market analysis
        run: |
          claude --version
          # Setup MCP configuration
          echo "设置 Claude MCP..."
          cp .mcp.example.json .mcp.json

          # Check environment
          echo "=== 环境检查 ==="
          echo "Python version:"
          python --version
          echo "uv version:"
          uv --version
          echo "uvx location:"
          which uvx

          # Test uvx with mcp-notify
          echo "=== 测试 uvx mcp-notify ==="
          uvx --version
          echo "尝试运行 mcp-notify..."
          timeout 5 uvx mcp-notify --help || echo "mcp-notify 命令测试完成"

          # Test uvx with mcp-aktools
          echo "=== 测试 uvx mcp-aktools ==="
          echo "尝试运行 mcp-aktools..."
          timeout 5 uvx mcp-aktools --help || echo "mcp-aktools 命令测试完成"

          # List MCP servers
          echo "=== Claude MCP 服务器列表 ==="
          claude mcp list

          # Run analysis
          echo "Custom Prompt: ${{ inputs.custom_prompt || '-' }}"
          echo "执行 AI 分析..."
          claude --dangerously-skip-permissions -p "${{ inputs.custom_prompt || '分析当前A股市场总结投资建议并推送到飞书机器人'}}"
        env:
          # Claude API
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}
          ANTHROPIC_AUTH_TOKEN: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
          ANTHROPIC_MODEL: ${{ secrets.ANTHROPIC_MODEL }}
          ANTHROPIC_SMALL_FAST_MODEL: ${{ secrets.ANTHROPIC_SMALL_FAST_MODEL }}
          # Market Data API
          OKX_BASE_URL: ${{ secrets.OKX_BASE_URL }}
          BINANCE_BASE_URL: ${{ secrets.BINANCE_BASE_URL }}
          # 企业微信群机器人
          WEWORK_BOT_KEY: ${{ secrets.WEWORK_BOT_KEY }}
          # 企业微信应用号
          WEWORK_APP_CORPID: ${{ secrets.WEWORK_APP_CORPID }}
          WEWORK_APP_SECRET: ${{ secrets.WEWORK_APP_SECRET }}
          WEWORK_APP_AGENTID: ${{ secrets.WEWORK_APP_AGENTID }}
          WEWORK_APP_TOUSER: ${{ secrets.WEWORK_APP_TOUSER }}
          WEWORK_BASE_URL: ${{ secrets.WEWORK_BASE_URL }}
          # 钉钉群机器人
          DINGTALK_BOT_KEY: ${{ secrets.DINGTALK_BOT_KEY }}
          DINGTALK_BASE_URL: ${{ secrets.DINGTALK_BASE_URL }}
          # 飞书/Lark群机器人
          FEISHU_BOT_KEY: ${{ secrets.FEISHU_BOT_KEY }}
          FEISHU_BASE_URL: ${{ secrets.FEISHU_BASE_URL }}
          LARK_BOT_KEY: ${{ secrets.LARK_BOT_KEY }}
          LARK_BASE_URL: ${{ secrets.LARK_BASE_URL }}
          # Bark
          BARK_DEVICE_KEY: ${{ secrets.BARK_DEVICE_KEY }}
          BARK_BASE_URL: ${{ secrets.BARK_BASE_URL }}
          # Telegram
          TELEGRAM_DEFAULT_CHAT: ${{ secrets.TELEGRAM_DEFAULT_CHAT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_BASE_URL: ${{ secrets.TELEGRAM_BASE_URL }}
